// House Diary
export const GET_ALL_DIARYS = "GET_ALL_DIARYS";
export const SET_ALL_DIARYS = "SET_ALL_DIARYS";
//작업일지, 경영일지
export const GET_CROPS = "GET_CROPS";
export const SET_CROPS = "SET_CROPS";
export const GET_WORK_CATEGORIES = "GET_WORK_CATEGORIES";
export const SET_WORK_CATEGORIES = "SET_WORK_CATEGORIES";
export const ADD_WORK_MANAGE_DIARY = "ADD_WORK_MANAGE_DIARY";
export const UPDATE_WORK_MANAGE_DIARY = "UPDATE_WORK_MANAGE_DIARY";
export const DELETE_WORK_MANAGE_DIARY = "DELETE_WORK_MANAGE_DIARY";
export const GET_WORK_MANAGE_DETAIL = "GET_WORK_MANAGE_DETAIL";
export const SET_WORK_MANAGE_DETAIL = "SET_WORK_MANAGE_DETAIL";
//생육정보
export const ADD_GROWTH_INFO = "ADD_GROWTH_INFO";
export const UPDATE_GROWTH_INFO = "UPDATE_GROWTH_INFO";
export const DELETE_GROWTH_INFO = "DELETE_GROWTH_INFO";
export const GET_GROWTH_DETAIL = "GET_GROWTH_DETAIL";
export const SET_GROWTH_DETAIL = "SET_GROWTH_DETAIL";
//영농일지 파일
export const ADD_UPDATE_FILE = "ADD_UPDATE_FILE";
export const DELETE_FILE = "DELETE_FILE";
//사진일지 사진 리스트
export const GET_IMAGE_DIARY_LIST = "GET_IMAGE_DIARY_LIST";

//영상 정보
export const GET_EVENT_VIDEOS = "GET_EVENT_VIDEOS";
export const SET_EVENT_VIDEOS = "SET_EVENT_VIDEOS";
export const GET_COMMENTS = "GET_COMMENTS";
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

//PheromoneTrap
export const SET_PHEROMONE_TRAP_STATE = "SET_PHEROMONE_TRAP_STATE";
export const GET_ALL_PHEROMONE_TRAP_LIST = "GET_ALL_PHEROMONE_TRAP_LIST";
export const SET_ALL_PHEROMONE_TRAP_LIST = "SET_ALL_PHEROMONE_TRAP_LIST";
